server:
  port: 8085

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

rabbitmq:
  exchanges:
    order: order.exchange
    dlx-exchange: dlx.exchange
  routing-keys:
    email: order.email.send
    dlx-email: dlx.email
  queues:
    email: email.queue
    dlx-email: dlx.email.queue

emails:
  sender_email: ${SENDER_EMAIL}
  sender_name: ${SENDER_NAME}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always